export const DIFFICULTIES = {
  easy: {
    label: 'Fácil',
    levelCount: 3,
    rows: { min: 8, max: 10 },
    cols: { min: 12, max: 16 },
    roomCount: { min: 3, max: 5 },
    roomSize:  { min: 3, max: 6 },
    enemyDensity: 0.03,
    enemyLevel: { min: 0, max: 0.3 },
    treasureDensity: 0.02,
    trapDensity: 0.01,
    potionDensity: 0.015,
    keyDensity: 0.005,
    hpMult: 1.0,
    atkMult: 0.8,
    enemyMoveDice: 1,
  },
  normal: {
    label: 'Normal',
    levelCount: 5,
    rows: { min: 10, max: 14 },
    cols: { min: 16, max: 22 },
    roomCount: { min: 4, max: 7 },
    roomSize:  { min: 3, max: 7 },
    enemyDensity: 0.05,
    enemyLevel: { min: 0, max: 0.6 },
    treasureDensity: 0.02,
    trapDensity: 0.02,
    potionDensity: 0.015,
    keyDensity: 0.005,
    hpMult: 1.3,
    atkMult: 1.0,
    enemyMoveDice: 1,
  },
  hard: {
    label: 'Difícil',
    levelCount: 7,
    rows: { min: 12, max: 18 },
    cols: { min: 20, max: 28 },
    roomCount: { min: 5, max: 9 },
    roomSize:  { min: 3, max: 7 },
    enemyDensity: 0.07,
    enemyLevel: { min: 0.2, max: 1.0 },
    treasureDensity: 0.015,
    trapDensity: 0.03,
    potionDensity: 0.01,
    keyDensity: 0.005,
    hpMult: 1.6,
    atkMult: 1.3,
    enemyMoveDice: 2,
  },
};
